# Generated by Django 3.0.6 on 2020-05-29 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='httpType',
            new_name='httpMethod',
        ),
    ]
