# Generated by Django 3.0.6 on 2020-06-05 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200530_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='checklist',
        ),
    ]
